### ISSUE TITLE
Cannot load any Pre-Trained Model

### ISSUE THREAD

**Issue by Mahyar-Ali** [HHousen/TransformerSum#15]
I created an extractive summarizer using the "extractive" module and the parser(almost all default values).
`from extractive import ExtractiveSummarizer`
`summarizer = ExtractiveSummarizer`
`args = build_parser()`
`model = summarizer(hparams=args)`
`checkpoint = torch.load(
            "epoch=3.ckpt", map_location=lambda storage, loc: storage
        )`
`model.load_state_dict(checkpoint["state_dict"])`
When I try to load a state dict in a model, it raises an error, **"RuntimeError: Error(s) in loading state_dict for ExtractiveSummarizer:
	Missing key(s) in state_dict: "word_embedding_model.embeddings.position_ids"."**

Sometimes with the missing keys error, it produces `IncompatibleKeys` and `shape mismatch` error.

Note: The model checkpoint file is of the same model name provided in the parser.
for build_parser, I just extracted all the arguments from the `main.py` file and placed it in a function.

It would be nice if you can document the necessary steps to load a pretrained model in the official documentation. As of now, I can't find any.
Thanks!

**Comment by HHousen** [comment]
I believe this is a duplicate of #12. Essentially, it is a problem with the update from 3.0.2 to 3.1.0 of huggingface/transformers. The problem is being discussed at huggingface/transformers#6882. While they work on a fix, you can install the previous version of huggingface/transformers by running `pip install -U transformers==3.0.2`.

The steps to load a pretrained model are in the documentation. Please see https://transformersum.readthedocs.io/en/latest/general/getting-started.html#programmatically. Simply import the `ExtractiveSummarizer` or `AbstractiveSummarizer` `pytorch_lightning` module and call the `load_from_checkpoint()` function with the path to the model checkpoint file.

**Comment by Mahyar-Ali** [comment]
Thanks....!
