### ISSUE TITLE
Problem in cloning repository mentioned in documentation to train an abstractive summarization model

### ISSUE THREAD

**Issue by silentghoul-spec** [HHousen/TransformerSum#43]
Hi,
I can't install
pip install git+https://github.com/HHousen/transformers.git@longformer_encoder_decoder
and 
pip install git+https://github.com/allenai/longformer.git@encoderdecoder.
It's saying repository doesn't exist.
Can you please correct the path of github directories?

**Comment by HHousen** [comment]
@silentghoul-spec Thanks for reporting this. This is because huggingface/transformers recently updated to [version 4.2.0](https://github.com/huggingface/transformers/releases/tag/v4.2.0), which added support for the LongformerEncoderDecoder. The LED is now an official model on the [huggingface/transformers documentation](https://huggingface.co/transformers/model_doc/led.html). Thus, it can now be used with the abstractive training code by specifying `--model_name_or_path allenai/led-base-16384`.

**Comment by silentghoul-spec** [comment]
Thanks for answering 😇

**Comment by HHousen** [comment]
Let me know if there are any issues with the new implementation.
