### ISSUE TITLE
Are the pretrained models of extractive summarization having the same metrics(Rouge score etc) on the datasets (WikiHow/Arxiv) as illustrated in model-results's CSV file ?

### ISSUE THREAD

**Issue by Suraj520** [HHousen/TransformerSum#47]
Hi @HHousen,
I was wondering if you can tell if the released checkpoints of Extractive models same as the one shown to output the metrics in the CSV file listed [here](https://transformersum.readthedocs.io/en/latest/extractive/models-results.html)

**Comment by HHousen** [comment]
@Suraj520 [That file](https://transformersum.readthedocs.io/en/latest/_static/summarization-model-experiments-raw-data.csv) is just an export of a table from the [TransformerSum Weights & Biases page](https://wandb.ai/hhousen/transformerextsum). The models in that file and on that page are the same as the released checkpoints. If you're looking at those values I'd recommend using the [Weights & Biases page](https://wandb.ai/hhousen/transformerextsum) instead of the CSV file since it lets you view and tweak the data how you want. If you filter using the "official" filter [in the table view](https://wandb.ai/hhousen/transformerextsum/table) you can see that stats for the released models.

**Comment by Suraj520** [comment]
Thanks for the update @HHousen :)
