### ISSUE TITLE
Cannot load a pre-trained model

### ISSUE THREAD

**Issue by KGuzikowski** [HHousen/TransformerSum#51]
I know this issue has been closed many times before but it seems like it doesn't work again. I cloned the repo and installed conda env as docs said. That installed `transformers=4.8.2`. Downgrading it to 3.0.2 (like it was suggested a year ago) isn't probably the best thing to do.
With transformers 4.8.2 I get:
```
RuntimeError: Error(s) in loading state_dict for ExtractiveSummarizer:
	Missing key(s) in state_dict: "word_embedding_model.embeddings.position_ids". 
```

When I do:

`model = ExtractiveSummarizer.load_from_checkpoint("../distilroberta-base-ext-sum.ckpt")`

I tried in Colab and locally with jupyter notebook.

**Comment by HHousen** [comment]
Thanks for searching the previous issues before opening one. When using the `main.py` script, you can specify the `--no_strict` argument. I believe that should fix it. When using `main.py` and encountering this error, you should be presented with [this message explaining the solution](https://github.com/HHousen/TransformerSum/blob/master/src/main.py#L62). Since you're not using `main.py`, try setting `strict=False` like so: `model = ExtractiveSummarizer.load_from_checkpoint("../distilroberta-base-ext-sum.ckpt", strict=False)`.

**Comment by KGuzikowski** [comment]
> Thanks for searching the previous issues before opening one. When using the `main.py` script, you can specify the `--no_strict` argument. I believe that should fix it. When using `main.py` and encountering this error, you should be presented with [this message explaining the solution](https://github.com/HHousen/TransformerSum/blob/master/src/main.py#L62). Since you're not using `main.py`, try setting `strict=False` like so: `model = ExtractiveSummarizer.load_from_checkpoint("../distilroberta-base-ext-sum.ckpt", strict=False)`.

Thank you very much! It works.
